alias ae='python -m tools.assemblage_edit'
alias mapv='python -m tools.map_visualizer'
alias brelease='bumpversion release'
alias bpatch='bumpversion --no-tag patch'
alias atlas='python -m tools.build_atlas  static/img/oryx_ur/$tile.png static/img/oryx_ur/$tile.txt static/img/oryx_ur/$tile.json'
alias tile_ids='python -m tools.make_tile_ids static/img/oryx_ur'
alias typeshed='cp -rf typeshed/* ~/.venv/autochthon/lib/mypy/typeshed/third_party/3'
alias typing='mypy --strict -p game'
alias rg="rg --iglob '!static/js/pixi*' --iglob '!typeshed'"
