_.propagate  # unused attribute (game/core/main.py:69)
_get_component  # unused function (game/core/world.py:143)
_get_components  # unused function (game/core/world.py:162)
paintEvent  # unused function (tools/assemblage_edit.py:96)
paintEvent  # unused function (tools/map_visualizer.py:386)
