# Stubs for tcod._internal (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def verify_order(order: Any): ...
def handle_order(shape: Any, order: Any): ...
