"""Constants of values for basic engine calculations."""


MOMENTS_PER_TURN = 100
MOVE_COST = MOMENTS_PER_TURN
ATTACK_COST = MOMENTS_PER_TURN
WAIT_COST = MOMENTS_PER_TURN
HIT_CHANCE = 0.5
DODGE_CHANCE = 0
PARRY_CHANCE = 0
