"""Constants of values for basic engine calculations."""
TIME_UNITS_PER_TURN = 100
MOVE_COST = TIME_UNITS_PER_TURN
ATTACK_COST = TIME_UNITS_PER_TURN
WAIT_COST = TIME_UNITS_PER_TURN
HIT_CHANCE = 0.5
DODGE_CHANCE = 0
BLOCK_CHANCE = 0
DEFLECT_CHANCE = 0
