# Stubs for tornado.platform.auto (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from time import monotonic as monotonic_time
from tornado.platform.posix import Waker as Waker, set_close_exec as set_close_exec
from typing import Any

def set_close_exec(fd: Any) -> None: ...
