# Stubs for tornado.platform.auto (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from time import monotonic as monotonic_time
from typing import Any

from tornado.platform.posix import Waker as Waker
from tornado.platform.posix import set_close_exec as set_close_exec

def set_close_exec(fd: Any) -> None: ...
