# Stubs for tornado.platform.epoll (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from tornado.ioloop import PollIOLoop

class EPollIOLoop(PollIOLoop):
    def initialize(self, **kwargs: Any) -> None: ...
