# Stubs for tornado.log (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import logging.handlers
from typing import Any, Optional

access_log: Any
app_log: Any
gen_log: Any

class LogFormatter(logging.Formatter):
    DEFAULT_FORMAT: str = ...
    DEFAULT_DATE_FORMAT: str = ...
    DEFAULT_COLORS: Any = ...
    def __init__(
        self,
        fmt: Any = ...,
        datefmt: Any = ...,
        style: str = ...,
        color: bool = ...,
        colors: Any = ...,
    ) -> None: ...
    def format(self, record: Any): ...

def enable_pretty_logging(options: Optional[Any] = ..., logger: Optional[Any] = ...): ...
def define_logging_options(options: Optional[Any] = ...): ...
