# Stubs for esper (Python 3.7)
from typing import Any, Generator, Tuple

class Processor:
    world: Any = ...
    def process(self, *args: Any, **kwargs: Any) -> None: ...

class World:
    _entities: Any = ...
    _components: Any = ...
    process_times: Any = ...
    def _clear_dead_entities(self) -> None: ...
    def __init__(self, timed: bool = ...) -> None: ...
    def clear_cache(self) -> None: ...
    def clear_database(self) -> None: ...
    def add_processor(self, processor_instance: Any, priority: int = ...) -> None: ...
    def remove_processor(self, processor_type: Any) -> None: ...
    def get_processor(self, processor_type: Any) -> Processor: ...
    def create_entity(self, *components: Any) -> int: ...
    def delete_entity(self, entity: Any, immediate: bool = ...) -> None: ...
    def component_for_entity(self, entity: Any, component_type: Any) -> Any: ...
    def components_for_entity(self, entity: Any) -> Generator[Any, None, None]: ...
    def has_component(self, entity: Any, component_type: Any) -> bool: ...
    def add_component(self, entity: Any, component_instance: Any) -> None: ...
    def remove_component(self, entity: Any, component_type: Any) -> None: ...
    def get_component(self, component_type: Any) -> Generator[Tuple[int, Any], None, None]: ...
    def get_components(self, *component_types: Any) -> Generator[Tuple[int, Any], None, None]: ...
    def try_component(self, entity: Any, component_type: Any) -> Generator[Any, None, None]: ...
    def process(self, *args: Any, **kwargs: Any) -> None: ...

CachedWorld = World
