import typing

C = typing.TypeVar("C")
P = typing.TypeVar("P")

class Processor:
    world: World
    def process(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...

class World:
    def __init__(self, timed: bool = False) -> None:
        self._entities: typing.Dict[int, typing.Dict[typing.Any, typing.Any]] = {}
    def clear_cache(self) -> None: ...
    def clear_database(self) -> None: ...
    def add_processor(self, processor_instance: Processor, priority: int = 0) -> None: ...
    def remove_processor(self, processor_type: Processor) -> None: ...
    def get_processor(self, processor_type: typing.Type[P]) -> P: ...
    def create_entity(self, *components: typing.Any) -> int: ...
    def delete_entity(self, entity: int, immediate: bool = False) -> None: ...
    def component_for_entity(self, entity: int, component_type: typing.Type[C]) -> C: ...
    def components_for_entity(self, entity: int) -> typing.Tuple[C, ...]: ...
    def has_component(self, entity: int, component_type: typing.Type[C]) -> bool: ...
    def add_component(self, entity: int, component_instance: C) -> None: ...
    def remove_component(self, entity: int, component_type: typing.Type[C]) -> int: ...
    def get_component(
        self, component_type: typing.Type[C]
    ) -> typing.Iterable[typing.Tuple[int, C]]: ...
    def get_components(
        self, *component_types: typing.Type[typing.Any]
    ) -> typing.Iterable[typing.Tuple[int, typing.Tuple[typing.Any, ...]]]: ...
    def try_component(self, entity: int, component_type: typing.Type[C]) -> typing.Iterator[C]: ...
    def process(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
